/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactFormInput {
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface ContactSubmission {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Project {
  'id' : bigint,
  'title' : string,
  'githubLink' : string,
  'description' : string,
  'demoLink' : string,
  'techStack' : Array<string>,
}
export interface Skill {
  'name' : string,
  'color' : string,
  'iconName' : string,
  'proficiency' : bigint,
}
export type SubmitResult = { 'ok' : bigint } |
  { 'err' : string };
export interface _SERVICE {
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getSkills' : ActorMethod<[], Array<Skill>>,
  'submitContact' : ActorMethod<[ContactFormInput], SubmitResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];